variables:
  container_name: "likelin-platform"
  docker_port: 12001

stages:
  - pre
  - build
  - deploy

pre:
  stage: pre
  script:
    - ls
    - docker stop ${container_name}
    - docker rm ${container_name}
  allow_failure: true


build:
  stage: build
  script:
    - echo ${container_name}:$CI_COMMIT_SHA
    - docker build -t ${container_name}:$CI_COMMIT_SHA .
    - docker images


deploy:
  stage: deploy
  script:
    - docker run  -p ${docker_port}:8080 -d --name ${container_name} ${container_name}:$CI_COMMIT_SHA
